### ISSUE TITLE
when use in combination with pagemod_speed

### ISSUE THREAD

**Issue by mxmkmarquette** [davinder17s/easy-gzip-cache#3]
if you use defer_javascript it's not able to actually find the files create by pagemod_speed .defer.js

**Comment by davinder17s** [comment]
Well i would like to mention, if you are using pagespeed already, then you
may be knowing, pagespeed works differently, but this script is more useful
and is kind of alternative to page speed

Pagespeed already removes, modifies the html code, and internally rewrites
it

On 04-May-2017 10:38 PM, "Maxime Marquette" <notifications@github.com>
wrote:

if you use defer_javascript it's not able to actually find the files create
by pagemod_speed .defer.js

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/davinder17s/easy-gzip-cache/issues/3>, or mute the
thread

**Comment by davinder17s** [comment]
Actually if you use pagespeed, then no script knows where are the actual files, other than pagespeed itself, which integrates itself with web server, so this script wont be able to help, but this script is more useful where no pagespeed is present and you need caching the right way
